// Encouragement words shown when a light is hit — deliberately daft and
// incongruous. Single words plus a few recognised phrases. Loaded before game.js.
var ENCOURAGEMENTS = [
  "Helical!","Marvellous!","Unlikely!","Lapwing!","Saucy!","Brioche!","Hovercraft!","Turbo!","Lumpy!","Harpsichord!",
  "Commendable!","Battenberg!","Marzipan!","Spicy!","Minty!","Buzzard!","Elliptical!","Pepper!","Elastic!","Samphire!",
  "Tamarin!","Sly!","Cactus!","Corking!","Dewy!","Kestrel!","Jacket Potato!","Lemur!","Verdant!","Custard!",
  "Most Triumphant!","Mantelpiece!","Deep Focus!","Bewildering!","Husky!","Goldfinch!","Modular!","Bespoke!","Tectonic!","Reasonable!",
  "Zesty!","Wizard!","A Bold Choice!","Righteous!","Corduroy!","Veranda!","Briny!","Dragon!","Long Take!","Absurd!",
  "Spatula!","Igneous!","Orbital!","Zippy!","Kinetic!","Estimable!","Resplendent!","Pure Cinema!","Badger!","Munificent!",
  "Francois Truffaut!","Phosphorescent!","Sparky!","Axolotl!","Kazoo!","Banana!","Well I Never!","Shiny!","Heron!","Ripping!",
  "Wry!","Treecreeper!","Mega!","Limpid!","Taffeta!","Eccles!","Crisp!","Venerable!","Pangolin!","Okapi!",
  "Avocet!","Tweed!","Furtive!","Astral!","Art Nouveau!","Drizzle!","Correct!","Bittern!","Piccolo!","Oblong!",
  "Pearly!","Pipistrelle!","Exquisite!","Hydraulic!","Ciabatta!","Goodness Gracious!","Alain Resnais!","Biscuit!","Jazzy!","Italian Neorealism!",
  "Spiffing!","Tagliatelle!","Grand!","Marten!","Mossy!","Newt!","Endive!","Damp!","Bold!","Dapper!",
  "Crumpet!","Robert Bresson!","Sensible!","Gobsmacked!","Parsnip!","Bullfinch!","Curious!","Tepid!","Bassoon!","Wombat!",
  "Stupendous!","Laser!","Chintz!","Theremin!","Perplexed!","Steady On!","Bakewell!","Wheelbarrow!","Triassic!","Clever!",
  "Agnes Varda!","Halcyon!","Wagtail!","Luminescent!","Sublime!","Quantum!","Doorknob!","Sufficient!","Pompous!","Swede!",
  "Wonky!","Goblin!","Vector!","Hedgehog!","Wholesome!","Dappled!","Regal!","Oboe!","Spry!","Gossamer!",
  "Greenfinch!","Marmalade!","Fantastic!","Marmoset!","Crumble!","Tapir!","Main Character!","Jean-Luc Godard!","Mighty!","Pneumatic!",
  "Tartan!","Tweedy!","Cupola!","Euphonium!","Perky!","Celestial!","Adequate!","Gnarly!","Satin!","Pumpernickel!",
  "Oystercatcher!","Plover!","Mohair!","Polite!","Brisk!","Baffling!","Clarinet!","Jaunty!","Buttery!","Dormouse!",
  "Big If True!","Eric Rohmer!","Rotund!","Gingham!","Daft!","Meteor!","Sincere!","Stoat!","Damask!","Bucolic!",
  "Chef's Kiss!","Otter!","Radiant!","Safe!","Stately!","Peppermint!","German Expressionism!","Twee!","Rhubarb!","Sovereign!",
  "Special!","Allotment!","Redshank!","Mandolin!","Ketchup!","Heroic!","Courgette!","Lavish!","Pixel!","Dubious!",
  "Living Legend!","Valid!","Claude Chabrol!","Aerodynamic!","Akira Kurosawa!","Velvet!","Mise en Scene!","Sparkly!","Kind!","Soft!",
  "Waxy!","Calico!","Effervescent!","Dunnock!","Flannel!","Ingmar Bergman!","Lush!","Cosmic!","Tessellated!","Prodigious!",
  "Smashing!","Serene!","Squat!","Gannet!","Flummoxed!","Pristine!","Peachy!","Tangy!","Skew!","Accordion!",
  "Dinky!","Brittle!","Sousaphone!","Coolness!","Cheddar!","Pudding!","Andrei Tarkovsky!","Noble!","Flapjack!","Cornet!",
  "Unforgivable!","Bagpipes!","Cracking!","Nougat!","Nifty!","Useful!","Pickle!","Tuesday!","Nocturnal!","Paisley!",
  "Photonic!","Vole!","Parkin!","Curlew!","Pancake!","Silky!","Muslin!","Beneficent!","Vivid!","Auteur Theory!",
  "Ethereal!","Velveteen!","Cinema Verite!","Plump!","Excellent!","Lute!","Wistful!","Transcendent!","Polecat!","Comet!",
  "Jaguar!","Nonplussed!","Numbat!","Crunchy!","Bamboozled!","Brocade!","Yeasty!","Walrus!","Askew!","Jump Cut!",
  "Wobbly!","Nuthatch!","Posh!","Moonlit!","Yasujiro Ozu!","Capybara!","Cloister!","Magnificent!","Befuddled!","Ineffable!",
  "Iridescent!","Gable!","French New Wave!","Practical!","Luminous!","Ferret!","Shrew!","Top of the Class!","Ocarina!","Fluffy!",
  "Laudable!","Scone!","Illustrious!","Good Heavens!","Glockenspiel!","Fizzy!","Manatee!","Cromulent!","Mongoose!","Aubergine!",
  "Timpani!","Turret!","Toast!","Murky!","Majestic!","Lithe!","Stoic!","Cretaceous!","Quokka!","Nouvelle Vague!",
  "Chaffinch!","Ergonomic!","Puffin!","Turnip!","Meerkat!","Gentle!","Zither!","Jacques Rivette!","Gazebo!","Glorious!",
  "Praline!","Sturdy!","Velour!","Tactical!","Vibraphone!","Eminent!","Portico!","Nimbus!","Bouncy!","Imperial!",
  "Gnocchi!","Lopsided!","Rotunda!","Thunder!","Salsify!","Deluxe!","Federico Fellini!","Frosty!","Nebula!","Sourdough!",
  "Chaotic!","Suave!","Electric!","Hessian!","Thermos!","Belfry!","Plucky!","No Notes!","Banjo!","Ukulele!",
  "Feral!","Brilliant!","Pergola!","Massive!","Lynx!","Focaccia!","Crunch!","Svelte!","Robust!","Weasel!",
  "Godwit!","Splendid!","Snazzy!","Smug!","Trifle!","Tiny!","Cardigan!","Fractal!","Piquant!","Kohlrabi!",
  "Ferocious!","Friendly!","Opalescent!","Cashmere!","Legal!","Galvanic!"
];
